language: python
python:
  - "2.7"

before_install:
    - export DJANGO_SETTINGS_MODULE=dashboard.settings
    - export PYTHONPATH=$HOME/builds/DLance96/ox-dashboard

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install psycopg2
script:
  - python manage.py test 
