language: python
python:
  - "2.7"

before_install:
    - export DJANGO_SETTINGS_MODULE=dashboard.settings
    - export PYTHONPATH=$HOME/builds/DLance96/ox-dashboard
    - export PIP_USE_MIRRORS=true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
before_script:
  – python manage.py migrate 
script:
  - python manage.py test 
